for code review
sobaotto/twitter-manage-app pull request #1
Opened 2021-03-19 11:37 UTC by sobaotto

2021-03-19 12:05 UTC, sadnessOjisan requested changes

2021-03-19 12:05 UTC, sadnessOjisan commented on public/js/create.js
>    const _switch = form.switch.value;
Q: この変数名はどうして _ から始まるのですか？

2021-03-19 12:18 UTC, sadnessOjisan requested changes

2021-03-19 12:18 UTC, sadnessOjisan commented on public/js/admin.js
l5: firestore の collection 名 は enum で管理しよう

```ts
const firestoreKeys = {
  functions: "functions"
}
```

2021-03-19 12:18 UTC, sadnessOjisan commented on public/js/admin.js
>      let Number = 0;
must: 変数名は小文字からです。ただ、そもそもこれは予約語なので、違う変数名を選んでください。

2021-03-19 12:18 UTC, sadnessOjisan commented on public/js/admin.js
>      snapshot.forEach((doc) => {
must: Number を使わなくても、forEach の第二引数で idx を取れたはずです。

2021-03-22 06:03 UTC, sobaotto commented on public/js/create.js
>    const _switch = form.switch.value;
予約後を回避しようとしたからです。
変数名を変更します。

2021-03-22 07:27 UTC, merged